#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /usr/bin/ddns -c /etc/ddns/config.json
        procd_set_param respawn 300 0 5 # threshold, timeout, retry
        procd_set_param file /etc/ddns/config.json
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param pidfile /var/run/ddns.pid
        procd_close_instance
}